# Generated by Django 5.1.6 on 2025-03-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="classteacher",
            unique_together={("class_id", "semester_id", "subject_id")},
        ),
    ]
