# Generated by Django 5.1.6 on 2025-03-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_alter_classteacher_unique_together"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="classteacher",
            name="unique_homeroom_per_class_per_semester",
        ),
        migrations.RenameField(
            model_name="classification",
            old_name="semester_id",
            new_name="semester",
        ),
        migrations.RenameField(
            model_name="classification",
            old_name="student_id",
            new_name="student",
        ),
        migrations.RenameField(
            model_name="classstudent",
            old_name="class_id",
            new_name="classroom",
        ),
        migrations.RenameField(
            model_name="classstudent",
            old_name="semester_id",
            new_name="semester",
        ),
        migrations.RenameField(
            model_name="classstudent",
            old_name="student_id",
            new_name="student",
        ),
        migrations.RenameField(
            model_name="classteacher",
            old_name="class_id",
            new_name="classroom",
        ),
        migrations.RenameField(
            model_name="classteacher",
            old_name="semester_id",
            new_name="semester",
        ),
        migrations.RenameField(
            model_name="classteacher",
            old_name="subject_id",
            new_name="subject",
        ),
        migrations.RenameField(
            model_name="classteacher",
            old_name="teacher_id",
            new_name="teacher",
        ),
        migrations.RenameField(
            model_name="grade",
            old_name="semester_id",
            new_name="semester",
        ),
        migrations.RenameField(
            model_name="grade",
            old_name="student_id",
            new_name="student",
        ),
        migrations.RenameField(
            model_name="grade",
            old_name="subject_id",
            new_name="subject",
        ),
        migrations.AlterUniqueTogether(
            name="classification",
            unique_together={("student", "semester")},
        ),
        migrations.AlterUniqueTogether(
            name="classstudent",
            unique_together={("classroom", "student", "semester")},
        ),
        migrations.AlterUniqueTogether(
            name="classteacher",
            unique_together={("classroom", "semester", "subject")},
        ),
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together={("student", "subject", "semester")},
        ),
        migrations.AddConstraint(
            model_name="classteacher",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_homeroom", True)),
                fields=("classroom", "semester"),
                name="unique_homeroom_per_class_per_semester",
            ),
        ),
    ]
