# Generated by Django 5.1.6 on 2025-03-14 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "school",
            "0003_remove_classteacher_unique_homeroom_per_class_per_semester_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="classification",
            name="semester",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="school.semester",
            ),
        ),
        migrations.AlterField(
            model_name="classstudent",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="school.class"
            ),
        ),
        migrations.AlterField(
            model_name="classstudent",
            name="semester",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="school.semester",
            ),
        ),
        migrations.AlterField(
            model_name="classteacher",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="school.class"
            ),
        ),
        migrations.AlterField(
            model_name="classteacher",
            name="semester",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="school.semester",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="semester",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="school.semester",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
