# Generated by Django 5.1.7 on 2025-03-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0005_alter_teacher_options_alter_teacher_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
