from enum import Enum

PAGINATE_BY = 10
NAME_MAX_LENGTH = 50
PHONE_MAX_LENGTH = 11
CHAR_MAX_LENGTH = 255
EMAIL_MAX_LENGTH = 100
CLASS_MAX_LENGTH = 100
RANK_MAX_LENGTH = 30
SUBJECT_MAX_LENGTH = 30
TIME_DEFAULT = 0
ROLE_MAX_LENGTH = 10
SCORE_MAX_DIGITS = 4
SCORE_DECIMAL_PLACES = 2
HOMEROOM_DEFAULT = False


class Role(Enum):
    TEACHER = "teacher"
    ADMIN = "admin"
